### ISSUE TITLE
allow the defective to disguise as special detective roles e.g. Sniffer, Sherriff, Vigilante 

### ISSUE THREAD

**Issue by Nathan22211** [AaronMcKenney/ttt2-role_def#3]

**Comment by AaronMcKenney** [comment]
Can you define what you mean by "disguise" here?

The way the Defective works right now is that it emulates the Detective as closely as possible while remaining on the Traitor team. That required a lot of hardcoding on my end.

When I began work on the Defective, I originally had the idea that it should emulate special detective roles as well (rather than merely forcing actual special detectives to be regular special detectives), but stopped when I realized that this would essentially require even more hardcoding. The Defective code base would need to be modified to personally address each special detective role, and would need to be updated every time that a new special detective role is made. For example, I would have to more or less copy/paste code for the Banker role I made into the Defective so that a "Defective Banker" can acquire money in the same way as a Banker.

If by "disguise" you mean merely appearing as that special detective role without having their abilities... that's not good for the Defectives. If a Defective visually looks like a Sheriff, but doesn't have the Sheriff's DeputyDeagle (or has a shoddy replica), then the 5+ Innocents will be able to quickly suss out that the "Sheriff" is a Traitor and murder them in 10 seconds flat.

**Comment by AaronMcKenney** [comment]
I totally forgot this was even opened. Anyways, someone else requested this feature through Steam and gave more details on how they wanted it: Essentially that the disguise be thin, only altering the displayed role and not actually changing any abilities or what have you. That should be good enough hopefully...

That feature has been implemented with these two git commits:
7bcdbe411e69af8a0b272f99fbfbd8da4c8b8d5a
862578ddfb4c9e560447cb2065010d233ca6a884
